title: "CCM App"
public-url: ""
url: '' ## NO TRAILING SLASHES!!/<--nope
port: 3000
timezone: America/Chicago
google-tag_key: false
permalink: pretty
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "/" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "webpack.config.js"
  - "buildtools/"
  - "postcss.config.js"
  - "docs/"
